server:
  port: ${CUSTOM.SERVER.PORT:9004}
  
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

### Configuracion de MongoDB con SpringBoot 3
spring:
  data:
    mongodb:
      uri: mongodb://mitocode:mitocode@localhost:27017/mitocodedb?authSource=admin

encrypt:
  key: luis-rh-key

# Configuracion de MongoDB con SpringBoot 2
# spring:
  # data:
    # mongodb:
      # host: localhost
      # port: 27017
      # username: miticode
      # password: miticode
      # database: miticodedb
      ## uri: mongodb://mitocode:miticode@localhost:27017
      #authentication-database: admin
